### ISSUE TITLE
Not getting Insights and it is showing camera inactive

### ISSUE THREAD

**Issue by raja1985** [Azure/KAN#232]
![image](https://user-images.githubusercontent.com/4569281/217308611-6bd1169c-e033-44d3-9054-1ec66cae3d67.png)
![image](https://user-images.githubusercontent.com/4569281/217308683-7089e970-d4d0-4ab9-865d-a92240a0d250.png)
![image](https://user-images.githubusercontent.com/4569281/217308722-20270ba7-0954-40d8-a27c-2ffadc62a829.png)
![image](https://user-images.githubusercontent.com/4569281/217308793-b67451eb-6f19-4e7f-bcb7-b67f71eb7647.png)
![image](https://user-images.githubusercontent.com/4569281/217309159-d2eca91d-9ad5-4de2-bc12-4c06d2d34771.png)

Hi Team,

I tried various AI models but not getting insights. I have attached the screenshots.

Please help.

Thanks,
Rajesh Keshri

**Comment by raja1985** [comment]
Application is hosted on k8s, we are using IOT edge compute device. Deployment showing deploying.

**Comment by raja1985** [comment]
CPU acceleration

**Comment by waitingkuo** [comment]
Hi @raja1985 do you mean that you install iot edge on a k8s cluster ? or deploy KAN portal in k8s?

**Comment by raja1985** [comment]
deploy KAN portal in k8s

**Comment by raja1985** [comment]
this ticket is resolved. As i got the results. I raised another ticket for other issue.
