### ISSUE TITLE
I tried to replicate vehicle attribute AI model from your URL mentioned in screenshot

### ISSUE THREAD

**Issue by raja1985** [Azure/KAN#235]
![image](https://user-images.githubusercontent.com/4569281/217856952-9498c5df-f71d-4564-b370-c994429ec4ff.png)
![image](https://user-images.githubusercontent.com/4569281/217857313-6251307c-05d1-4ed4-9697-2b92354d590d.png)
![image](https://user-images.githubusercontent.com/4569281/217857563-e6d2b9ac-e132-4e4d-95c6-b57ab4eb5fe2.png)
![image](https://user-images.githubusercontent.com/4569281/217857649-9b2d3fe9-f36f-4a65-a635-f7bc02afcff8.png)
![image](https://user-images.githubusercontent.com/4569281/217858178-ceb9eb49-900c-4140-8829-816e6c6a154d.png)
![image](https://user-images.githubusercontent.com/4569281/217858295-8c7c39c6-7417-4bec-8278-7705887b038d.png)
![image](https://user-images.githubusercontent.com/4569281/217858399-1024c528-2aa1-415d-a03a-6ef590b28b9c.png)
![image](https://user-images.githubusercontent.com/4569281/217858929-652bf92c-cf4d-4a7b-b868-9af34e94440e.png)

Hi Team,

I tried to replicate the complex-AI-skill URL model but it is not generating any data.

Please see the screenshots and let me know where i am doing wrong.

Thanks,
Rajesh

**Comment by Haishi2016** [comment]
Hi @raja1985, one thing you can try is to relax the confidence threshold to see if any events coming through. Also, you might want to use Discord channel to ask questions to the team.

**Comment by raja1985** [comment]
Hi Haishi,

I changed the confidence(0 to 90) but don't see the results. Please send me Discord channel link.

**Comment by Haishi2016** [comment]
The discord link is on the home page: https://github.com/azure/kan. Based on your latest issue report, you were able to progress pass this? Should this issue be closed?

**Comment by raja1985** [comment]
No it is not yet resolved. Please help me to resolve this. After relaxing the confidance also, results did not come.

**Comment by Haishi2016** [comment]
Can you please follow the troubleshooting guide here to narrow down the problem: https://github.com/Azure/KAN/blob/main/docs/guide/troubleshoot.md?

**Comment by raja1985** [comment]
Hi Haishi,

i did troubleshooting. After removal of Filter node i got some results that also only black color is only coming. when lower the confidence level to 5 with filter node not getting the result.

**Comment by raja1985** [comment]
please setup a call. Discord channel is blocked by our company.

**Comment by raja1985** [comment]
Any reply?

**Comment by Haishi2016** [comment]
Please send me an email address to hbai@microsoft.com so I can schedule a Teams call. Thanks!

**Comment by raja1985** [comment]
Please schedule it between 10am IST to 10pm IST

**Comment by Haishi2016** [comment]
Hi @raja1985, we don't support filtering on attributes. Instead, you can filter based on object detection tags such as "vehicles" or "pedestrians". The tutorial is wrong. We'll make a fix to the tutorial soon. Sorry for the confusion!

**Comment by raja1985** [comment]
Application doesn't support filter attributes
