### ISSUE TITLE
There is a issue with person-detection default model

### ISSUE THREAD

**Issue by raja1985** [Azure/KAN#236]
Hi Team,

There is issue with person detection model. It is detecting other objects as person.

Please correct it or let me know if i am doing anything wrong.

Thanks,
Rajesh

![image](https://user-images.githubusercontent.com/4569281/218019036-249754b6-32fe-4012-86d8-4e021e12d528.png)

**Comment by Haishi2016** [comment]
Hi @raja1985, as you see, the detection confidence is rather low on those objects, as expected. You can add a filter to your AI skill to filter out low-confident detections.

**Comment by raja1985** [comment]
resolved
