### ISSUE TITLE
Switch from K8s API to KAN API when performing CRUD operations on solutions, targets and instances

### ISSUE THREAD

**Issue by Haishi2016** [Azure/KAN#239]
We need to switch from calling K8S API directly to calling KAN API when we perform CRUD operations on solutions, targets and instances. This will enable non-K8s deployments, and it will allows us to track API usages better.

**Comment by ronpai** [comment]
Besides the basic CRUD operations, we uses K8S service API to access the **kan-service-ext** to get the load balancer ingress IP (KAN url) and also  the network API to get the ingress (portal URL)

**Comment by Haishi2016** [comment]
Can we make those configuration parameters?

**Comment by ronpai** [comment]
Currently we retrieve kan-api address / portal ingress address through direct k8s api call and set the value to target / solution config upon creation.
Is there another way to retrieve the value without direct k8s api?
