### ISSUE TITLE
Custom model training screen picks up wrong model type

### ISSUE THREAD

**Issue by Haishi2016** [Azure/KAN#243]
For an object detection custom model:

![image](https://user-images.githubusercontent.com/19833345/219549244-26a55dfa-5dc5-460d-b058-dbfb341b8b39.png)

The training screen prompts to have a least 2 tags:

![image](https://user-images.githubusercontent.com/19833345/219548952-3afb5041-f8e0-475d-8357-d8e6f8f443c1.png)

However, for object detection models, single tag should be allowed.

**Comment by ronpai** [comment]
Fixed in #261
