### ISSUE TITLE
failed to download kan and kanportal repo during setup without Azure

### ISSUE THREAD

**Issue by keeper7ka** [Azure/KAN#245]
Hello,

I'm trying to setup KAN  without Azure on local Kubernetes according the tutorial:
https://github.com/Azure/KAN/blob/main/docs/tutorial/setup-guide.md

Here are my kan-installer.sh selections:
![image](https://user-images.githubusercontent.com/19428678/221415463-d5eaf7b0-d320-4621-ba97-6ea456b76d67.png)

Kubernetes found, Ingres installed ,  but then i receive errors:

_Installing kan
Release "kan" does not exist. Installing it now.
**Error**: **failed to download "oci://kanprod.azurecr.io/helm/kan"** (hint: running `helm repo update` may help)
We faced some issues while pull kan from container registry. Please try the installer again a few minutes later
Installing Portal
Release "kanportal" does not exist. Installing it now.
**Error**: **failed to download "oci://kanprod.azurecr.io/helm/kanportal"** (hint: running `helm repo update` may help)
We faced some issues while pull KANportal from container registry. Please try the installer again a few minutes later_

"helm repo update" - doesn't help.

Any ideas?

Thanks,
Andrey

**Comment by Haishi2016** [comment]
I believe this is a transient error. Sometimes pulling from the ACR may fail. Retrying, at a later time, generally fixes the problem.

**Comment by keeper7ka** [comment]
> I believe this is a transient error. Sometimes pulling from the ACR may fail. Retrying, at a later time, generally fixes the problem.
No changes after 3 months! 
Here the log minute ago:


Installing kan
Release "kan" does not exist. Installing it now.
Error: failed to download "oci://kanprod.azurecr.io/helm/kan" (hint: running `helm repo update` may help)
We faced some issues while pull kan from container registry. Please try the installer again a few minutes later
Installing Portal
Release "kanportal" does not exist. Installing it now.
Error: failed to download "oci://kanprod.azurecr.io/helm/kanportal" (hint: running `helm repo update` may help)
We faced some issues while pull KANportal from container registry. Please try the installer again a few minutes later

**Comment by Haishi2016** [comment]
What's your Helm version?

**Comment by keeper7ka** [comment]
> What's your Helm version?

~$ helm version
version.BuildInfo{Version:"**v3.2.0**", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}

**Comment by Haishi2016** [comment]
Please try to update to Helm 3.8 or later, as per https://github.com/Azure/KAN/blob/main/docs/tutorial/setup-guide.md.

**Comment by Haishi2016** [comment]
Closing for no activities
