### ISSUE TITLE
Unable to Link Camera to AI Skill - Dropdown is empty

### ISSUE THREAD

**Issue by JMH-Jarbydev** [Azure/KAN#249]
I've got all setup, the computing device, the camera, the model, and the AI Skill, but when I tried to run the deployment and link the camera to the AI Skill the Dropdown is empty.
Any Clue?

Thanks

<img width="1560" alt="image" src="https://user-images.githubusercontent.com/69280541/222294509-23ccc822-adf5-4f77-8db5-d39d315bbb2c.png">

**Comment by Haishi2016** [comment]
HI, @JMH-Jarbydev, can you please confirm if the AI Skill exist on the AI Skills page? Thanks

**Comment by ronpai** [comment]
Hi @JMH-Jarbydev 
Since we have some verification on that, only the skills that match the acceleration of the compute device would be displayed at the dropdown page. 
Please check whether the acceleration of compute device and skill aligns, thanks!

**Comment by Haishi2016** [comment]
Close for no activities.
