### ISSUE TITLE
Install script fails when $KUBECONFIG is not set

### ISSUE THREAD

**Issue by rlfmendes** [Azure/KAN#251]
When $KUBECONFIG is not set, setup fails even if K8s is installed. Here's the error:

Installing ingress
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp 127.0.0.1:8080: connect: connection refused

Need to add a check for this condition.

**Comment by ronpai** [comment]
Hi @rlfmendes,
For the "aks" section in the installer, a valid kubeconfig is required to achieve the installing process. If there is no current kubernetes context in the environment, you can select "use an existing one" to choose existing AKS kubeconfig.
Thanks!
