### ISSUE TITLE
Adding Custom Containers to the Nodes in the Pipeline

### ISSUE THREAD

**Issue by jaypaddy** [Azure/KAN#253]
Currently the Nodes in the pipeline are activities which are implemented by KAN. for example, Camera Input, Filter etc. Could we have a node in the Pipeline such that it can be a Docker Container that gets packaged as part of the solution and gets deployed?

For example i want to construct a pipeline as follows:

Camera Input > Filter > Enrichment [Custom Container] > ML Inference > Rules Engine [Customer Container] > Http Output

Being able to define all this as a single Skill including the custom containers?

**Comment by Haishi2016** [comment]
You can define a custom node that implements a gRPC interface. You can self-host the gRPC server and provide the gRPC endpoint to KAN, or, you can configure your container image that implements the gRPC interface and KAN will host it on your behalf. Please see this doc for more details: https://github.com/Azure/KAN/blob/main/docs/tutorial/How-to-BYOM.md

**Comment by Haishi2016** [comment]
Closing for no activities.
